tilt-dev/tilt-extensions

README.md
conftest/README.md
conftest/Tiltfile

@victorwuky as mentioned in the docs.

Added an extension and docs for running Conftest in Tilt

---

.circleci/config.yml
Makefile
README.md
namespace/README.md
namespace/Tiltfile
namespace/test/Tiltfile
namespace/test/deployment.yaml
namespace/test/job.yaml
namespace/test/test.sh
test.sh

Hello @landism, @victorwuky,
Please review the following commits I made in branch nicks/ch3204:
5e84d9be3a0375e808bbafe9bfd7c0ae7dd6f9d7 (2020-05-27 10:14:24 -0400)
Add an extension for manipulating namespaces. Fixes https://github.com/tilt-dev/tilt/issues/3204

Add an extension for manipulating namespaces. Fixes https://github.com/tilt-dev/tilt/issues/3204

---

git_resource/README.md
helm_remote/README.md
helm_remote/Tiltfile

@nicks you beat me getting #25 merged before I got these changes in 😛

Update documentation with some links

---

helm_remote/Tiltfile

Hello @jazzdan,
Please review the following commits I made in branch nicks/gannan08/crds:
3eadab901154cc1b53ae2e8e6da8d2bb787785f6 (2020-06-12 12:35:56 -0400)
Fix compatibility issues with `head` provided by MacOS X.

Fix compatibility issues with `head` provided by MacOS X.

---

restart_process/README.md

Please review the following commits I made in branch maiamcc/restart-proc-readme:
1bad3466fa1afeff6bb71dbb38d78d7d9b3231c5 (2020-06-12 12:01:40 -0400)
restart_process: readme tweaks and doc links

restart_process: readme tweaks and doc links

---

git_resource/Tiltfile

remove use of `head`

---

local_output/README.md

Hello @jazzdan,
Please review the following commits I made in branch maiamcc/fix-copypasta:
a8f19c0926e0d5b0202f14f8ac0a1d9482f76771 (2020-06-15 12:54:48 -0400)
local_output: fix copypasta

local_output: fix copypasta

---

restart_process/release.sh

Hello @jazzdan,
Please review the following commits I made in branch nicks/restart:
70f13f2b82c3dd1fbd625ac0594290f229e5b72f (2020-06-25 11:35:36 -0400)
fix a bug in the restart_process release script

fix a bug in the restart_process release script

---

namespace/test/deployment.yaml

Hello @nicks,
Please review the following commits I made in branch nicks/namespace-test:
ecd9b7a1e72e233d6ac7f600974f94c8ddc76776 (2020-06-25 13:00:50 -0400)
namespace: add a readiness probe to the test to avoid race conditions

namespace: add a readiness probe to the test to avoid race conditions

---

helm_remote/Tiltfile

helm_remote - fix grep command for mac

---

helm_remote/Tiltfile

--version is not part of `helm repo add`
https://helm.sh/docs/helm/helm_repo_add/

remove '--version' from 'helm repo add'

---

README.md
namespace/Tiltfile
secret/README.md
secret/Tiltfile
secret/test/.pgpass
secret/test/Tiltfile
secret/test/job.yaml
secret/test/test.sh
test.sh

Hello @jazzdan, @landism,
Please review the following commits I made in branch nicks/secret:
1f708350d271ae4ec2bbdda8030f098f7c81d441 (2020-07-09 14:58:00 -0400)
secret: add an extension for creating secrets

secret: add an extension for creating secrets

---

helm_remote/Tiltfile
helm_remote/test/Tiltfile

cc @KOGI 
what do you think of this as an alternative to https://github.com/tilt-dev/tilt-extensions/pull/56 ? does it work inside your mingw setup?

helm_remote: make all the tests pass on windows

---

restart_process/Tiltfile

Test forthcoming in the Tilt repo
Fixes #52

restart_process: force root user so live update always works

---

secret/README.md

Hello @nicks,
Please review the following commits I made in branch nicks/type:
4a78114c7d0fce90932676947af1713aa2b9e474 (2020-08-13 09:27:34 -0400)
[secret] added docs on the new param

[secret] added docs on the new param

---

helm_remote/Tiltfile

Hello @landism, @kogi,
Please review the following commits I made in branch nicks/windows:
292ac51b9c803d3b9ad3d91dde7cae51ab6edd51 (2020-08-24 11:52:51 -0400)
helm_remote: make sure tests pass on windows

helm_remote: make sure tests pass on windows

---

helm_remote/README.md
helm_remote/Tiltfile

Hello @landism, @kogi,
Please review the following commits I made in branch nicks/issue72:
694eb208a11cdf1bc7e75521103c1894b8c6eddf (2020-08-24 12:41:37 -0400)
helm_remote: by default, don't create a namespace. Fixes https://github.com/tilt-dev/tilt-extensions/issues/72
ecec3b643411690c23bee07ca9e641b7b68b1516 (2020-08-24 12:30:29 -0400)
helm_remote: make sure tests pass on windows
Fixes https://github.com/tilt-dev/tilt-extensions/issues/74

helm_remote: by default, don't create a namespace. Fixes https://github.com/tilt-dev/tilt-extensions/issues/72

---

README.md
file_sync_only/Tiltfile
file_sync_only/test/Tiltfile
file_sync_only/test/test.sh
test.sh

1) Make sure it works when Tilt is using a private registry (for KIND or Microk8s)
2) Make the tests part of the tilt-extensions CI

minor improvements to file_sync_only extension

---

helm_remote/Tiltfile

Hello @nicks,
Please review the following commits I made in branch nicks/helm-v3.3.2:
ed84db12969a634e7ede36adc6a1d15451de20f7 (2020-09-18 13:12:20 -0400)
helm_remote: add a dumb fix for helm 3.3.2. Fixes https://github.com/tilt-dev/tilt-extensions/issues/83

helm_remote: add a dumb fix for helm 3.3.2. Fixes https://github.com/tilt-dev/tilt-extensions/issues/83

---

README.md

Hello @nicks,
Please review the following commits I made in branch nicks/badge:
89929bcb63ec09447a6c17f38477f3f5a37ad3a6 (2020-09-18 14:14:06 -0400)
add a circleci badge

add a circleci badge

---

README.md
snyk/README.md
snyk/Tiltfile

Adds a `snyk` extension to test k8s yaml files :)
Not sure it that's what I'm supposed to do, but @nicks - do you mind reviewing this?

feat: add snyk IaC extension

---

min_k8s_version/Tiltfile

min_k8s_version: allow non-numeric characters in versions

---

restart_process/README.md
restart_process/Tiltfile
restart_process/test/custom.Tiltfile
restart_process/test/test-custom.sh
restart_process/test/test-docker.sh
restart_process/test/test.sh

Hello @maiamcc,
Please review the following commits I made in branch nicks/restart:
e1576155b4fab12aa7c6e62b5a02969a325364c6 (2020-10-30 13:16:32 -0400)
restart_process: add custom_build_with_restart

restart_process: add custom_build_with_restart

---

.circleci/Dockerfile
.circleci/config.yml

Hello @nicks,
Please review the following commits I made in branch nicks/circleci:
564888ad1d3ef0489ebb02088139fedc42b109da (2020-11-03 17:12:55 -0500)
roll some CI steps into the image

roll some CI steps into the image

---

.github/workflows/workflow.yml

Hello @nicks,
Please review the following commits I made in branch nicks/github-actions:
f400516a7ce95b59a8acdd1e6cb3331e83924253 (2020-11-19 18:06:14 -0500)
github actions: upgrade setup-go

github actions: upgrade setup-go

---

README.md
kubebuilder/README.md
kubebuilder/Tiltfile

@nicks Can you double check the Tiltfile? Line 26 especially feels a bit embarrassing, but I couldn't find the proper way.
Video will follow after this is approved.

add kubebuilder extension

---

git_resource/Tiltfile

Fix tag support for initial clones, too 😊 
@nicks

Git Tag Support - Part Deux

---

syncback/Tiltfile
syncback/verify_rsync.sh

Hello @nicks,
Please review the following commits I made in branch maiamcc/syncback-rsync-version:
d9da20d0f9448352e94155888cfb411a62a29b2f (2020-12-09 17:52:48 -0500)
syncback: verify local rsync and sufficient version

syncback: verify local rsync and sufficient version

---

syncback/README.md

Hello @nicks,
Please review the following commits I made in branch maiamcc/syncback-gotcha:
0353483484a51ef71d195dbf95273cfe50ee34d0 (2020-12-15 11:43:31 -0500)
syncback: document local deletion gotcha

syncback: document local deletion gotcha

---

git_resource/README.md
git_resource/Tiltfile

Add default ssh-forwarding to git_resource docker builds

---

.circleci/config.yml
README.md

Hello @nicks,
Please review the following commits I made in branch nicks/ci:
d8a5edc15e3ce2a9c25e2495688cb8579fa90c9d (2021-01-11 20:21:48 -0500)
circleci: upgrade docker, fix the badge

circleci: upgrade docker, fix the badge

---

helm_remote/Tiltfile

helm repo update/search don't have --username --password flags -
https://helm.sh/docs/helm/helm_repo_update
https://helm.sh/docs/helm/helm_search/
What I did- 
* remove auth from search
* remote auth from update

repo update dont have --username

---

kubebuilder/Tiltfile

configurable controller-gen options

---

git_resource/README.md
git_resource/Tiltfile

Add support for specific revisions of a git repo

---

global_vars/README.md
global_vars/Tiltfile

Initial creation of global_vars extension

---

git_resource/Tiltfile
git_resource/test/Tiltfile

Hello @kogi, @maiamcc,
Please review the following commits I made in branch nicks/issue135:
ac4d02e9fba259582b8e3291fcb8cf83969c61d4 (2021-03-03 15:58:56 -0500)
git_resource: improvements to url parsing
- handle URLs with the format http://user@host/
- handle repositories where "master" is not the default repo branch
fixes https://github.com/tilt-dev/tilt-extensions/issues/135

git_resource: improvements to url parsing

---

.circleci/Dockerfile
.circleci/config.yml

Hello @nicks,
Please review the following commits I made in branch nicks/ci:
2b2bfc16b8ed1330da27d824cc9c50791c21af3f (2021-03-08 17:31:19 -0500)
test: add 'make' to ci image

test: add 'make' to ci image

---

namespace/Tiltfile

@nicks 
I just did this through the UI, so I don't know how to also edit the docs in here, but they should be updated, as well.
Whether or not this is a reasonable default is a different question.

Passthrough allow_duplicates

---

test.sh
tests/golang/test/Tiltfile
tests/golang/test/fake_project/foo/bar/failing_test.go
tests/golang/test/fake_project/foo/baz_test.go
tests/golang/test/fake_project/go.mod
tests/golang/test/fake_project/slow/slow_test.go
tests/golang/test/test.sh
tests/javascript/test/test.sh

Tests for tests/golang extension as requested in #148 
Will do js tests tomoro

tests for go test ext

---

Makefile
README.md
podman/README.md
podman/Tiltfile
podman/test/Dockerfile
podman/test/Tiltfile
podman/test/deployment.yaml
podman/test/index.html
podman/test/main.sh
podman/test/test.sh
test.sh

Please review the following commits I made in branch nicks/podman:
27d73fb91a488193d98525d36e444f61bc916c8f (2021-04-13 13:16:34 -0400)
Add a podman extension

Add a podman extension

---

restart_process/tilt-restart-wrapper.go

I have seen a typo in the module

Fixes a typo in the comment

---

cert_manager/test/Tiltfile
cert_manager/test/test.sh
test.sh

Hello @nicks,
Please review the following commits I made in branch nicks/certmanagertest:
0ef3dc281a5393a66c75e90d30101a07466a3f07 (2021-05-26 10:34:19 -0400)
cert_manager: add tests

cert_manager: add tests

---

.circleci/Dockerfile
.circleci/config.yml
tilt_inspector/package.json

Hello @nicks,
Please review the following commits I made in branch nicks/inspector:
333157f955bc69e3d8f05b26d9f77d4e48d69dbc (2021-06-28 13:10:44 -0400)
tilt_inspector: update

tilt_inspector: update

---

.circleci/Dockerfile
.circleci/config.yml
tilt_inspector/package.json

Reverts tilt-dev/tilt-extensions#191

Revert "tilt_inspector: update"

---

tests/javascript/test/Tiltfile.test

Hello @nicks,
Please review the following commits I made in branch nicks/testtest:
049da5162ee6a7b34dbef0515c9c4b709be50f93 (2021-07-01 15:10:10 -0400)
test: update test to use new result format

test: update test to use new result format

---

secret/README.md

fix README.md example

---

list_port_forwards/README.md
list_port_forwards/Tiltfile
list_port_forwards/display_port_forwards.sh

Creates a new resource that lists all port forwards in use.

add port forwards listing

---

file_sync_only/test/manifest.yaml
file_sync_only/test/test.sh

Hello @nicks,
Please review the following commits I made in branch nicks/filesynconly:
2bd75b2a23210fbf812788c944cd38d2fc86cefc (2021-07-16 15:19:44 -0400)
file_sync_only: improve tests in preparation for https://github.com/tilt-dev/tilt/pull/4768

file_sync_only: improve tests in preparation for https://github.com/tilt-dev/tilt/pull/4768

---

cancel/README.md
cancel/reconcile_cancel_btn.sh
cancel/test/Tiltfile
cancel/test/test.sh
cancel/test/trigger.sh

Please review the following commits I made in branch nicks/cancel:
e741865e2a40b5e2e9c2c792f496f47619916df3 (2021-08-13 20:10:43 -0400)
cancel: add tests, fix bugs

cancel: add tests, fix bugs

---

kubefwd/README.md
kubefwd/Tiltfile
kubefwd/run-kubefwd.sh
kubefwd/sudo-kubefwd.sh

Hello @milas, @landism,
Please review the following commits I made in branch nicks/kubefwd:
2bdd4dadf37a9f6e62c5c25668c2df7acb2e0a02 (2021-08-24 12:35:30 -0400)
kubefwd: initial pass at a kubefwd extension

kubefwd: initial pass at a kubefwd extension

---

helm_remote/Tiltfile

fixed the issue when failing on repos with more than 1 chart

updated get_local_repo

---

README.md
dotenv/README.md
dotenv/Tiltfile
dotenv/test/.env
dotenv/test/Tiltfile

Title says it all. This was a minor annoyance not to have so i made a small extension for it.

dotenv: add simple .env loading ext

---

uibutton/Tiltfile
uibutton/test/Tiltfile

Fixed uibutton for tilt docker-prune.
Fixed long strings and syntax.

Fix for uibutton

---

syncback/verify_rsync.sh

Please review the following commits I made in branch nicks/rsync:
cf917e587cdd82534b6429f738fe5bdc690cc388 (2021-10-29 14:49:33 -0400)
update rsync regex. Fixes https://github.com/tilt-dev/tilt-extensions/issues/255

update rsync regex. Fixes https://github.com/tilt-dev/tilt-extensions/issues/255

---

kubectl_build/test/Dockerfile
kubectl_build/test/Tiltfile
kubectl_build/test/deployment.yaml
kubectl_build/test/index.html
kubectl_build/test/main.sh
kubectl_build/test/test.sh

Hello @nicks,
Please review the following commits I made in branch nicks/kubectlbuild:
e532da1bf98e0aa35e34f1c281739a8f9aa97b65 (2021-11-04 13:09:41 -0400)
kubectl_build: add tests
ab698efd55daa7680a3685bea898f49f7872b564 (2021-11-04 12:38:47 -0400)
circleci: update ci image to go 1.17

kubectl_build: add tests

---

ko/test/Tiltfile
ko/test/cmd/hello-world/kodata/index.html
ko/test/cmd/hello-world/main.go
ko/test/deployment.yaml

Hello @nicks,
Please review the following commits I made in branch nicks/kodata:
ee7603833ddf30b74688e1d6ccadcc816f6f4b86 (2021-11-08 16:33:21 -0500)
ko: flesh out the ko test a bit

ko: flesh out the ko test a bit

---

ko/README.md
ko/Tiltfile
ko/test/.ko.yaml
ko/test/Tiltfile

Please review the following commits I made in branch nicks/kodata:
77d1fdeac28b45b13053819ac49e6c2bfd0445f5 (2021-11-08 16:55:19 -0500)
ko: add kwargs for the ko extension
ee7603833ddf30b74688e1d6ccadcc816f6f4b86 (2021-11-08 16:33:21 -0500)
ko: flesh out the ko test a bit

ko: add kwargs for the ko extension

---

.circleci/Dockerfile
.circleci/config.yml
ko/test/Tiltfile
kubectl_build/test/test.sh
test.sh

Please review the following commits I made in branch nicks/tests:
cd9866356a929991409ab5d8824970e5a74f9090 (2021-11-18 11:26:45 -0500)
tests: fix all tests :grimace:

tests: fix all tests :grimace:

---

README.md
knative/README.md
knative/Tiltfile
knative/test/Dockerfile
knative/test/Tiltfile
knative/test/index.html
knative/test/main.sh
knative/test/service.yaml
knative/test/test.sh

Hello @milas,
Please review the following commits I made in branch nicks/knative:
6751b2e07826c30b75d03ddbcc92e28dcdcf9190 (2021-11-17 18:49:17 -0500)
knative: add an extension for installing knative and deploying knative-based resources

knative: add an extension for installing knative and deploying knative-based resources

---

test.sh

Hello @nicks,
Please review the following commits I made in branch nicks/knative3:
062e31934474181e2719bf1bd81b366d2e6e3d06 (2021-11-23 14:17:16 -0500)
test: disable the knative test for now

test: disable the knative test for now

---

README.md
k8s_attach/README.md
k8s_attach/Tiltfile
k8s_attach/test/Tiltfile
k8s_attach/test/deployment.yaml
k8s_attach/test/index.html
k8s_attach/test/main.sh
k8s_attach/test/test.sh

Hello @milas,
Please review the following commits I made in branch nicks/attach:
e055d45cd5c84b060e7286dbfb871ed9dd9c5ea1 (2021-12-10 09:29:28 -0500)
k8s_attach: an extension that can monitor and live_update existing servers

k8s_attach: an extension that can monitor and live_update existing servers

---

kim/Tiltfile

kim: Windows support

---

helm_resource/README.md
helm_resource/Tiltfile
helm_resource/test/Tiltfile

Hello @nicksieger, @milas,
Please review the following commits I made in branch nicks/resource:
1c39966026c2e53fbb7d44b08f541bc3eefbc856 (2022-01-10 20:50:33 -0500)
helm_resource: add support for helm repos

helm_resource: add support for helm repos

---

.circleci/Dockerfile
.circleci/config.yml
Makefile
README.md

- ci: move tilt-extensions-ci image to gcr.io
- Add deployment to main README

Move extensions image to gcr.io

---

honeycomb/events.py
honeycomb/test/Dockerfile
honeycomb/test/Tiltfile
honeycomb/test/crd.yaml
honeycomb/test/events_test.py
honeycomb/test/um.yaml

Please review the following commits I made in branch nicks/honeycomb-events:
b764d7ad3c91c2172a49ccbb505e0315f777fdf5 (2022-01-21 10:25:38 -0500)
honeycomb: add tests
356b9addca93c1839e0a89d05283348dd9b0ff18 (2022-01-11 12:34:46 -0500)
Don't require python 3.9
b3c6f160ec5cfcceb88c4db4f86ba4eebea9ddd0 (2022-01-11 12:03:35 -0500)
fix typo
55789e3c24419ccfb80ae04401248cd697e3f2c8 (2022-01-11 11:55:26 -0500)
add try catch so there are no errors on old Tilt versions
407a7d5100d1a5829ef2b704674b9d76e697245e (2022-01-10 21:46:16 -0500)
honeycomb: support custom_build
* Code is suitably …

honeycomb: support custom_build and add tests"

---

secret/README.md
secret/Tiltfile

Please review the following commits I made in branch nicks/secret2:
62299cd775dcb1d9c6884d8b9146343b564010a7 (2022-02-07 19:01:15 -0500)
secret: add a function for TLS certs

secret: add a function for TLS certs

---

coreos_prometheus/Tiltfile
git_resource/Tiltfile

Please review the following commits I made in branch nicks/root:
2903011223c2edee1b12169e3915f3e04881c525 (2022-02-14 13:25:01 -0500)
more shlex.quote for path escaping

more shlex.quote for path escaping

---

uibutton/Tiltfile

Noticed this one was missing when I went to use it.

uibutton: Add support for requires_confirmation parameter

---

uibutton/Tiltfile

Hello @nicks,
Please review the following commits I made in branch nicks/uibuttion:
ba56ef7e13d24bf39d6b07a207678ccc4bfbdd94 (2022-03-04 12:00:25 -0500)
Revert "Add requires_confirmation support to uibutton (#351)"
This reverts commit be667fc490e53ff4f2fdf8b3f11ba6d54179de14.

Revert "Add requires_confirmation support to uibutton (#351)"

---

.circleci/config.yml
Makefile

Hello @nicks,
Please review the following commits I made in branch nicks/update:
fdb33b225363d57688222cc38dd3552a982bfebf (2022-03-07 13:44:07 -0500)
circleci: bump tilt version on ci

circleci: bump tilt version on ci

---

syncback/krsync.sh

Please review the following commits I made in branch nicks/syncback2:
007a70a71b889e8d0f57caa28b5b4cbd5bb478cb (2022-03-09 12:44:07 -0500)
syncback: another attempt at fixing CI errors

syncback: another attempt at fixing CI errors

---

pulumi/README.md
pulumi/test/Tiltfile

Hello @nicks,
Please review the following commits I made in branch nicks/pulumi2:
b0b1c2a908d2b81080fde2281eb09feee050afbd (2022-03-16 12:19:29 -0400)
pulumi: add live update example

pulumi: add live update example

---

helm_resource/README.md
helm_resource/Tiltfile
helm_resource/helm-apply-helper.py
helm_resource/helm-delete-helper.py
helm_resource/test/Tiltfile

Hello @nicksieger, @milas,
Please review the following commits I made in branch nicks/helmresource:
78e330fcce176a2d1a20a81ca796ab67fab79cb0 (2022-03-16 10:53:35 -0400)
helm_resource: rewrite in python to ensure windows compatibility

helm_resource: rewrite in python to ensure windows compatibility

---

helm_resource/helm-apply-helper.py

Please review the following commits I made in branch nicks/set:
f721465b5c5b86a38424a0cb5958ddc77e770d0d (2022-04-06 16:26:51 -0400)
helm_resource: default our own namespaces
fixes https://github.com/tilt-dev/tilt-extensions/issues/374

helm_resource: default our own namespaces

---

pulumi/test/test.sh

Hello @nicks,
Please review the following commits I made in branch nicks/pulumi5:
f8857760532abf41e7207bd5e8d9366819bc19f1 (2022-04-08 16:40:11 -0400)
test: it's ok if the pulumi user check failed

test: it's ok if the pulumi user check failed

---

knative/Tiltfile

Hello @landism, @nicksieger,
Please review the following commits I made in branch nicks/knative:
47304a89899ef6ecbff3d29c07f30ea170994ff4 (2022-04-15 14:25:35 -0400)
knative: avoid deadlocks on 'tilt down'

knative: avoid deadlocks on 'tilt down'

---

.circleci/Dockerfile
.circleci/config.yml
README.md
earthly/README.md
earthly/Tiltfile
earthly/test/Earthfile
earthly/test/Tiltfile
earthly/test/deployment.yaml
earthly/test/index.html
earthly/test/main.sh
earthly/test/test.sh

Hello @nicks,
Please review the following commits I made in branch nicks/earthly2:
ffe653dedaf3c4fc914225b3e2189262000427d5 (2022-06-13 16:53:31 -0400)
update CI images
13e1b75350da2f426e91c02bb3cc813c42402211 (2022-06-01 17:10:46 +0200)
earthly: add better explanation to ignore and deps
ca2e7409d1ed970023fbc940c23c5aca49ba8548 (2022-05-27 15:05:37 +0200)
earthly: disable allow-privileged flag by default
64ef59f6b859df838b3a514c6df31b691a2a1c1f (2022-05-27 14:29:16 +0200)
earthly: add context arg
8a397a545ae7b6d9aa4f4ba3b6ba06fc96b2a8a8 (2022-05-26 23:28:43 +0200)
earthly: fix install command
b410fd670856d1a8a5cd52cb10dbccc2c2d22667 (2022-05-26 18:17:44 +0200)
earthly: use ARG as opposed to ENV for EARTHLY_VERSION
72dd09a938c3dc66a229e0f0313845091fde38d7 (2022-05-26 15:19:11 +0200) …

add earthly extension

---

ngrok/README.md
ngrok/Tiltfile
ngrok/ngrok-reconcile-config.sh
ngrok/ngrok-run.sh

https://ngrok.com/docs/guides/upgrade-v2-v3
Do I need to add compability for Ngrok v2 agent (v1 config)?
Also added a flag for specifying default_ngrok_config.

feat(ngrok): Ngrok extension to support V3

---

helm_resource/helm-apply-helper.py

Reverts tilt-dev/tilt-extensions#413

Revert "helm_resource: fix helm_resource() so it will deploy to custom namespaces"

---

helm_resource/helm-apply-helper.py
helm_resource/test/Tiltfile
helm_resource/test/helloworld/templates/systemconfig.yaml

Please review the following commits I made in branch nicks/namespace-semantics:
61f98c54b6af50bf500893108c07bfadc76f334e (2022-06-27 18:15:49 -0400)
helm_resource: add a test for charts with multiple namespaces

helm_resource: add a test for charts with multiple namespaces

---

.circleci/config.yml

Please review the following commits I made in branch nicks/pulumi4:
293894bbe7ac85df9c6c5e71fb897c260a81e085 (2022-06-27 18:23:56 -0400)
test: remove pulumi secrets from circleci

test: remove pulumi secrets from circleci

---

README.md

Hello @nicks,
Please review the following commits I made in branch nicks/flake:
5a0dc4966d222f21fed79a98eadd070a8ec81b65 (2022-07-05 11:59:15 -0400)
add nix_flake to the main readme

add nix_flake to the main readme

---

helm_resource/helm-apply-helper.py
helm_resource/namespacing.py
helm_resource/namespacing_test.py
helm_resource/test/Tiltfile
helm_resource/test/helloworld/templates/service-list.yaml

Hello @milas,
Please review the following commits I made in branch nicks/traefik:
79908363454226bbd87839ad239a3afa184e8d40 (2022-07-05 14:29:11 -0400)
helm_resource: improve namespace defaulting. fixes https://github.com/tilt-dev/tilt-extensions/issues/419

helm_resource: improve namespace defaulting

---

helm_resource/Tiltfile
helm_resource/helm-apply-helper.py
helm_resource/test/Tiltfile

Signed-off-by: Mark Mixson <mixson_mark@bah.com>
fixes #435

Adds Windows support to helm_resource (#435)

---

uibutton/README.md
uibutton/Tiltfile
uibutton/test/Tiltfile

Followup from: https://github.com/tilt-dev/tilt/pull/5900

UIButton: Add choice_input / dropdown selections

---

uibutton/README.md
uibutton/Tiltfile
uibutton/test/Tiltfile

Exposes the `env` argument on `uibutton`.

UIButton: Expose env

---

uibutton/Tiltfile
uibutton/test/Tiltfile

Fixes: #384 #193 #332 
I smoke tested the case from #193 to confirm that renamed buttons now get cleaned up properly

Use builtins for uibutton extension

---

.gitignore
coreos_prometheus/Tiltfile

fixes https://github.com/tilt-dev/tilt/issues/5947

core_prometheus: fix a syntax error now that starlark is a bit stricter

---

.circleci/Dockerfile
.circleci/config.yml
Makefile

Signed-off-by: Nick Sieger <nick@nicksieger.com>

ci: update to go 1.19; upgrade kubectl build, pack, earthly

---

.circleci/Dockerfile
.circleci/config.yml

Signed-off-by: Nick Sieger <nick@nicksieger.com>

ci: fix earthly permissions

---

knative/test/Tiltfile

Signed-off-by: Nick Sieger <nick@nicksieger.com>

knative: install 1.8.0 for test/CI

---

global_vars/README.md

Correct title in global_vars/README.md

---

restart_process/Tiltfile

Reverts tilt-dev/tilt-extensions#541

Revert "fix(restart_process): work around sticky /tmp"

---

snyk/Tiltfile

Adds labels parameter to the snyk extension to support grouping of snyk resources.

Add support for grouping to snyk extension

---

podman/README.md
podman/Tiltfile
podman/test_restart/Dockerfile
podman/test_restart/Tiltfile
podman/test_restart/deployment.yaml
podman/test_restart/index.html
podman/test_restart/main.sh
podman/test_restart/test.sh
test.py

Add `podman_build_with_restart()` function to Podman extension.
@nicks fyi

Podman: add restart function

---

tests/javascript/README.md
tests/javascript/Tiltfile
tests/javascript/test/Tiltfile.test

This PR adds a `test_jest_pnpm` function to the same great functionality of the tests extension!
Happy to add tests for this; wanted to consider the best approach with a maintainer! 🙏

feat: init `test_jest_pnpm`

---

secret/README.md
secret/Tiltfile
secret/test/Tiltfile

secrets: add helpers for docker registry and ECR

---

helm_resource/README.md
helm_resource/Tiltfile
helm_resource/helm-apply-helper.py

fixes https://github.com/tilt-dev/tilt-extensions/issues/528

helm_resource: allow images to be injected twice

---

.gitignore
pypiserver/Tiltfile
pypiserver/test/Tiltfile

aligns it with the other tilt extensions
that manage cache state

pypiserver: update extension cache management

---

coreos_prometheus/Tiltfile
git_resource/Tiltfile
helm_remote/Tiltfile
pypiserver/Tiltfile

updates the name and docs to better reflect what this function does today

[chore] update cache load function

---

helm_resource/namespacing.py
helm_resource/namespacing_test.py

fixes https://github.com/tilt-dev/tilt-extensions/issues/607

helm_resource: correctly handle DOS line endings

---

helm_remote/README.md
helm_remote/Tiltfile

fix: adds option to disable helm_remote install_crds

---

.pre-commit-config.yaml
helm_resource/helm-apply-helper.py
helm_resource/namespacing.py
helm_resource/namespacing_test.py
honeycomb/events.py
honeycomb/honeycomb-collector.py
honeycomb/test/events_test.py
list_dependencies/deps.py
pulumi/pulumi-get.py
pypiserver/src/is_port_used.py
pyproject.toml

Runs ruff with the F,E,W (=flake8 Python base line linter) + I (isort).

Enable .py linting with ruff via pre-commit hook and fix findings

---

restart_process/Dockerfile
restart_process/Tiltfile
restart_process/release.sh

updates images with changes from https://github.com/tilt-dev/tilt-extensions/pull/626

restart_process: update helper image

---

.circleci/config.yml
Makefile
publish-ci-image.sh

ci: publish new image with latest ctlptl and kind

---

uibutton/README.md
uibutton/Tiltfile
uibutton/test/Tiltfile

uibutton: accept env var as Dict[str, str]

---

.circleci/Dockerfile
.circleci/config.yml

dockerfile: use go 1.24

---

earthly/test/Tiltfile
earthly/test/restart.Tiltfile
earthly/test/test.sh

earthly: debug CI test failures
