- README.md
- min_tilt_version/README.md
- min_tilt_version/Tiltfile
Adds `min_tilt_version` function to allow you to codify your minimum requirements. 
This solves the time old issue when working on a team and adding new features to tilt and having tilt output some cryptic error message saying some feature/function doesn't work and teammates not knowing to upgrade tilt. 
References https://github.com/windmilleng/tilt/issues/3125  but I believe this is a much better solution to that same problem
References https://github.com/windmilleng/tilt/issues/3159 (but I see there is a native implementation already in PR https://github.com/windmilleng/tilt/pull/3172/files )
I am submitting this since I already built it, but obviously native version is nicer.
p.s I think requiring a readme for each plugin is a nice touch.
> Add min tilt version plugin

- README.md
- pack/README.md
- pack/Tiltfile
First pass at an extension for using pack. There are a few arguments on `pack` that would be useful to expose here as well, but this covers the main use case I think.
@victorwuky as mentioned in the docs.
> An extension to use pack and buildpacks to build container images

- restart_process/.gitignore
- restart_process/Dockerfile
- restart_process/Tiltfile
- restart_process/main.go
- restart_process/release.sh
- restart_process/tilt-restart-wrapper.go
problem: using `entr` as a solution for restarting processes meant we had to run `echo filename | entr...` ie had to run wrapped in `sh -c` which meant that args specified in k8s yaml would never take effect (because they were applied to the `sh` call rather than the user's executable)
solution: compilee a wrapper for `entr` so we can invoke it without piping
> restart_process: use pre-compiled bin of entr that doesn't need to be run as shell

- README.md
- restart_process/README.md
- restart_process/Tiltfile
- restart_process/release.sh
- restart_process/tilt-restart-wrapper.go
Please review the following commits I made in branch maiamcc/restart-container-docs:
ec3e7d824e93bda035079f8805f8f23cb127258d (2020-04-22 13:04:58 -0400)
under the hood explanation
95b04b5bf9fed274426bcd4f64df93e324f230d5 (2020-04-22 12:54:18 -0400)
do footnotes work on github?
c9c4f605eaf0d3d1f23b8fa709e825399f3689e3 (2020-04-22 12:34:41 -0400)
usage docs
> docs for restart_process extension

- restart_process/README.md
- restart_process/Tiltfile
Please review the following commits I made in branch maiamcc/stupid-error:
4dd6719f0a7073eaab47103786830db6d3b3635e (2020-04-28 17:40:57 -0400)
restart_process: ugh get the script name right
> restart_process: ugh get the script name right

- README.md
- helm_remote/README.md
- helm_remote/Tiltfile
@victorwuky
The currently recommended way of installing remote helm files is:
```python
local("helm upgrade --install <chart> <repo>")
```
But this has a few shortcomings when running `tilt down`:
1. the helm chart is not uninstalled
1. any namespace created with helm's `--create-namespace` flag is not uninstalled (even when using `tilt down --delete-namespaces`
Another option is:
```python
local("helm pull <repo>/<chart> --untar --destination helm_deps/<chart>")
k8s_yaml(helm("helm_deps/<chart>", namespace=myNamespace))
```
This has the advantage of solving bullet #1 above, but still has other shortcomings
1. namespace must already exist in order to install there (`helm()` has no support for `--create-namespace`)
1. even if namespace already exists, it still may not be cleaned up when …
> Add `helm_remote` extension

- namespace/test/Tiltfile
Hello @nicks,
Please review the following commits I made in branch nicks/parallel:
3df1829e28cb1748eebd870e4ad5ed9c52c90264 (2020-06-12 12:39:30 -0400)
disable parallelism until https://github.com/tilt-dev/tilt/issues/3421 is fixed
> disable parallelism until https://github.com/tilt-dev/tilt/issues/3421 is fixed

- git_resource/Tiltfile
> fix git pull command when in a headless state (as in when checking out a tag)

- git_resource/Tiltfile
Not sure how it ever worked before...
Before this change, if specifying a branch/tag name in your repo url as such: `git@github.com/owner/repo.git#branchName`, the command generated was akin to `git clone git@github.com/owner/repo.git#branchName -b branchName ./path/to/checkout`
Where the existence of that hash-tagged branch name was confusing to git (naturally so)
After this change, the same input results in a generated command of `git clone git@github.com/owner/repo.git -b branchName ./path/to/checkout`
> fix git checkout when specifying a branch name

- git_resource/Tiltfile
> fix failure to pass `port_forwards` to remote git checkouts

- git_resource/Tiltfile
- helm_remote/Tiltfile
Now that #3452 has been merged, it's possible for tiltfiles to be nested, and this breaks (in a way) both the `helm_remote` and `git_resource` extensions. With nested tiltfiles, it's now possible that these extensions create their private file caches in the nested location from which they're running, rather than in the tilt root directory. This PR fixes that.
> determine the tilt root location before establishing file caches

- .circleci/config.yml
- .gitignore
- git_resource/README.md
- git_resource/Tiltfile
- git_resource/test/.tiltignore
- git_resource/test/Tiltfile
- git_resource/test/test.sh
- helm_remote/README.md
- helm_remote/Tiltfile
- helm_remote/test/Tiltfile
- test.sh
Hello @kogi, @jazzdan,
Please review the following commits I made in branch nicks/macos:
d2dbdb9cbcb4f4c0384efab4cf3d80adb62591fc (2020-06-25 11:21:16 -0400)
Fix how the helm_remote and git_resource extensions handle cache directories.
Starlark freezes the module after loading, and won't let you set
globals in the module.
also adds tests for git_resource
> Fix how the helm_remote and git_resource extensions handle cache directories.

- git_resource/Tiltfile
if:
- a git resource has already been cloned/checkedout locally (pointing to "branch A")
- and a new branch (branch B) is pushed to origin
- the tiltfile is updated to use that branch
then:
- we get an error saying the new branch (branch B) was not found
----
This PR fixes that by fetching all from the remote server before attempting a checkout
> support changing branches to one that may not exist in the local repo

- helm_remote/Tiltfile
Hello,
I am trying to migrate my current architecture with local helm charts to remote charts with your awesome plugin.
My charts repository is private (with basic auth) so I discovered when the command tries to pull my chart that it was rejected because of not providing credentials.
I edited the extension to pass credentials to the command (like it is made lower in the code).
However, i have not experience with Python and I do not know if my approach is the good one. But, it works well ! :)
I will be happy to listen your feedback about it and to know what it is the correct solution to fix that.
Thank you for your work !
> fix: add auth flags for add repo command

- helm_remote/README.md
- helm_remote/Tiltfile
Hello,
I added a new parameter for the function `helm_remote` in case of we need to name a release with a different name of its chart`s name.
My use case is that I have a chart called `base` and i launch two services `myServiceOne` and `myServiceTwo` from this same chart (the chart is the same but `values.yaml` are different.
In the current case, if i give `myServiceOne` as name the script will try to download `myRepo/myServiceOne` while the targeted chart is called `myRepo/base`. With this new option, targeted chart stays `base` but helm function is called with the wanted name. :)
Thank you for your work <3
> feat: add release_name parameter to helm_remote

- helm_remote/Tiltfile
Hello,
I noticed that at the end in my local folder `.helm/`, i have not all my remote chart, but only one. It is because the remove command remove the root folder instead of the specific chart. This PR fixes the issue :)
Thank you for your work !
> helm_remote: remove specific chart instead of global directory

- restart_process/README.md
Hello @landism, @nicks,
update the restart_process readme to reflect the actual deprecation
of `restart_container` as of https://github.com/tilt-dev/tilt/pull/3551
> restart_process: update docs to reflect that update_container is actually deprecated [ch5904]

- restart_process/Dockerfile
Previous size (measured with `docker image inspect aaaaaa --format '{{.Size}}'`):
240996873 bytes = 240 MB
New size:
8546985 bytes = 8.5 MB
> restart_process: reduce image size

- min_k8s_version/README.md
- min_k8s_version/Tiltfile
Hello @nicks !
Here's the initial idea I came up with for enforcing a minimum tilt version. The functionality is heavily inspired by the min_tilt_version extension. Would something like this address the raised issue? (https://github.com/tilt-dev/tilt/issues/3297)
> tiltfile: added extension to enforce minimum k8s version

- helm_remote/Tiltfile
fix #67 
cc @KOGI 
I'm not very familiar with this extension and have made some guesses and tried to add comments to document my understanding. I'd like corrections if I'm wrong!
From the [helm docs](https://helm.sh/docs/chart_template_guide/control_structures/):
> {{- (with the dash and space added) indicates that whitespace should be chomped left
I can't think of a reason to filter by templates that happen to be doing whitespace chomping and I'm guessing it just happened that a crd encountered during development was doing chomping.
> helm_remote: filter out crds w/ `{{` instead of `{{-`; try to add some clarifying comments

- secret/Tiltfile
Hello,
I added an option on secret extension to specify the type of secret. Indeed, this is necessary for `docker-registry` secret to be detected and correctly work. :)
It seems to be good with me. Any feedback is welcome !
Thank you for your work !
> [secret] add ability to specify the type of secret

- helm_remote/Tiltfile
- helm_remote/test/Tiltfile
- min_tilt_version/Tiltfile
Hello @landism, @kogi,
Please review the following commits I made in branch nicks/duplicate:
5398d7c7a7f3f7275771f1944902dc3602cba299 (2020-08-13 10:07:13 -0400)
helm_remote: allow charts with duplicate yaml
also fix the version checks for dev builds
> helm_remote: allow charts with duplicate yaml

- docker_build_sub/Tiltfile
- restart_process/Tiltfile
The `docker_build_sub` and `docker_build_with_restart` extensions work by appending a suffix to an existing image to rename it, and then defining a new image with the original name, starting from that renamed image.
The default suffix used is "-base", which is kind of a logical suffix for users to take for themselves. If they already have an image by that name, they get a confusing error message like `Image dependency cycle: docker.registry.domain.com/my-project-base`, which doesn't give them a lot to go on, especially since theoretically this base image is an implementation detail of the extension and they shouldn't need to know about it.
Change the default suffix to something that:
1. is far less likely to conflict with any existing image names
2. makes it more likely that a user seeing …
> extensions: use more specific image suffix

- git_resource/Tiltfile
This Pull Request modifies `git_checkout` to prevent unnecessary checkouts during teardown by testing if `config.tilt_subcommand` == "up"
> Prevents git checkout during teardown

- README.md
Hello @nicks,
Please review the following commits I made in branch nicks/prom:
ddfef808bc9f55cf4bd8ec85e4e56be374e4972c (2020-09-16 18:43:41 -0400)
add coreos_prometheus to the extensions readme
> add coreos_prometheus to the extensions readme

- git_resource/Tiltfile
Hi. Some of our git repos use submodules. This change makes sure that submodules are always up to date (and as no effect on repos without submodules).
Something you guys would be open to merging upstream?
> Initialize and update submodules during git checkout

- git_resource/Tiltfile
Another small pain point. At least with my git configuration, checking out a branch by name only checks out my local branch and not the one we just fetched from `origin`. So, it still needs a `git pull` to update after checkout or the code is still on my last-merged/fetched commit. This change just makes sure we always check out the `origin/*` ref for the branch that was just fetched.
> Checkout fetched branch from origin on git update

- README.md
- cert_manager/README.md
- cert_manager/Tiltfile
Add an extension for deploying cert-manager and wait to it for being properly working by following the process described in the cert-manager documentation (https://cert-manager.io/docs/installation/kubernetes/#verifying-the-installation)
A working instance of cert-manager is required before calling `k8s_yaml` for any controller developed with Kubebuilder/using validation webhooks.
This extension makes it easier to get a working instance of cert-manager in the Tiltfile of all these projects
@victorwuky
> Add cert-manager extension

- README.md
- wait_for_it/README.md
- wait_for_it/Tiltfile
This extension can be useful in situations like waiting for some service until it is healthy/ready.
_if you decide to approve this PR, i would be so happy if you label it as `hacktoberfest-accepted`_. 
Happy Hacktober!
> Add wait_for_it extension

- restart_process/Dockerfile
- restart_process/Tiltfile
- restart_process/release.sh
- restart_process/test/Dockerfile
- restart_process/test/Tiltfile
- restart_process/test/fail.sh
- restart_process/test/job.yaml
- restart_process/test/test.sh
- test.sh
Addresses https://github.com/tilt-dev/tilt-extensions/issues/92
([Our fork of entr is here](https://github.com/tilt-dev/entr))
Test case: https://github.com/tilt-dev/failing-job
> restart_process: use our fork of entr to return exit code of user command

- README.md
- snyk/README.md
- snyk/Tiltfile
This expands upon the original `snyk` extension by adding the following capabilities:
* Added the ability to run container and open source tests, in addition to iac tests
* Ability to supply additional options to the Snyk CLI
* Tests are set to TRIGGER_MODE_MANUAL so as to not fire off tests for every code change
@victorwuky
@shaimendel
> snyk: add additional testing capabilities

- min_k8s_version/Tiltfile
issue: 
A variable is incorrectly named in the min_k8s_version Tiltfile. Because of this below error is received when `tilt up` is executed. 
```
~# tilt up
Tilt started on http://localhost:10350/
v0.17.9, built 2020-10-19
(space) to open the browser
(s) to stream logs (--stream=true)
(t) to open legacy terminal mode (--legacy=true)
(ctrl-c) to exit
Tilt started on http://localhost:10350/
v0.17.9, built 2020-10-19
Initial Build • (Tiltfile)
WARNING: You are running Kind without a local image registry.
Tilt can use the local registry to speed up builds.
Instructions: https://github.com/tilt-dev/kind-local
Beginning Tiltfile execution
local: tilt version
Successfully loaded Tiltfile (5.262713173s)
Traceback (most recent call last):
/root/Tiltfile:5:1: in <toplevel>
Error: cannot load …
```
> variable name fix for min_k8_version tilt file

- current_namespace/README.md
- current_namespace/Tiltfile
This can be used to automate your Tiltfile dynamically by fetching the
current namespace and using it within your Tiltfile using string
templates.
All you would have to do then would be to change your namespace using
something like `kubens "your-namespace"` before running `tilt up`.
@victorwuky 
@shaimendel
> Add extension for current_namespace

- README.md
Hello @nicks,
Please review the following commits I made in branch nicks/namespace:
cacfca2a25b80fa22227cc8e65f39f23d3664af2 (2020-11-12 15:19:51 -0500)
add current_namespace to the readme
> add current_namespace to the readme

- kubebuilder/Tiltfile
When clicking a resource with that has a slash in the name on the sidebar, I get e.g. `No match for /r/Watch/Compile`.
> fix kbuilder remove slash from resource name

- git_resource/README.md
- git_resource/Tiltfile
This allows specifying a tag name as the resource branch. Tags are a special case, and things break if you try to do `git checkout origin/tagName` or `git checkout origin/tags/tagName`, so we must rewrite to `git checkout tags/tagName`
@nicks 
@victorwuky
> add support for tag references

- syncback/Tiltfile
In this PR:
* docstrings (will also drop these into the readme, along with usage instructions)
* container support (`container` arg lets you specify container on the pod to act on)
* option to sync all of sync_dir instead of specifying individual paths
> syncback: docstring, container support, option to sync all of src_dir

- syncback/README.md
- syncback/Tiltfile
Flagged by @djcp (🙏🏻):
> One issue with this: if you set paths to include the entire repo (so empty), this'll remove your `.git/` directory in the host because of the `--delete` directive and how it interacts with default ignores.  Probably an explicit additional `excludes` option could fix this.
Not convinced that this API (`paths` is NON-optional, pass `[]` to watch entire dir) is the right API, but I wanted to make it a little harder to watch the entire dir/make sure it's a deliberate choice when it happens, b/c it's a dangerous option and you need to set your `ignore` values correctly or you risk blowing away data. Not quite sure how to do this tho, thoughts?
(Also, called the parameter `ignore` to match `docker_build` params, but happy for it to be whatever--`ignores`? `excludes`?)
> syncback: default excludes, can pass excludes

- helm_remote/README.md
- helm_remote/Tiltfile
Refactored helm_remote Tiltfile to remove the pessimism, and only perform changes when required
This stops the endless looping issue without having to change your `.tiltiginore`
resolves (my reported) issue https://github.com/tilt-dev/tilt-extensions/issues/116 and contains other improvements
also noticed a few spots for improving security, namely avoiding directory traversal from arbitrary inputs, especially because `rm` is involved with this.
This prevents chart/repo names like `something/../../` or `something && cat /etc/passwd` from being entertained, and shell 
**Changes** (there's no breaking changes)
- Fixed the indefinite loop that was possible due to how remote helm charts were being handled 
- Chart will only be re-downloaded to filesystem (`helm pull`) when required
- this is …
> helm_remote fix endless chart update loop + security improvements

- snyk/README.md
- snyk/Tiltfile
Adds support for different trigger modes, and a switch to control the exit code for gating or information only. Tidy up arg names, update README
> Tidy up extension, add support for trigger modes and info only

- restart_process/README.md
- restart_process/Tiltfile
Hello @nicks,
Please review the following commits I made in branch maiamcc/trigger-restart:
6c931432023458dca9507f305c7077f231014098 (2021-01-15 12:27:37 -0500)
restart_process: optional trigger arg to only restart process when specified files change
Addresses #122
> restart_process: optional trigger arg to only restart process when specified files change

- min_tilt_version/Tiltfile
This change solves the issue of paths and other binaries conflicting with the name.
In my case, there's a RubyGem called tilt that also has the binary called tilt installed and was taking the precedence (because of the Ruby version manager).
Having the environment variable available, I can now have it configured and the check can be performed targeting the correct binary location.
> Configurable location of binary

- helm_remote/Tiltfile
@nicks 
As part of its process, helm_remote() calls `helm repo update` to be sure its using the latest version of the chart. However, if the project contains multiple helm_remote() calls for different charts in the same repository, it would call `helm repo update` EACH time. This was having significant performance impacts on the time required to process the initial Tiltfile.
> Prevent fetching updates multiple times if we're already up to date

- cert_manager/README.md
- cert_manager/Tiltfile
Hi,
as requested on this following [issue](https://github.com/kubernetes-sigs/cluster-api/issues/4256#issuecomment-792630611), I have changed the default version for the cert-manager module.
I have tried to maintain the backward compatibility for version 0 too.
Furthermore, I have removed the `existCheck` because the [issue related](https://github.com/kubernetes-sigs/cluster-api/issues/4256#issuecomment-792630611) has been already fixed, so I think it is not required anymore!
Thanks
> Update the Cert Manager module version to 1.1.0 as default

- .circleci/config.yml
Hello @nicks,
Please review the following commits I made in branch nicks/ci:
e9a299adb523424b0c728bc38728df1d2b48386e (2021-03-19 19:06:39 -0400)
ci: update ci to use ctlptl to create a cluster
> ci: update ci to use ctlptl to create a cluster

- tests/javascript/README.md
- tests/javascript/Tiltfile
- tests/javascript/test/Tiltfile
- tests/javascript/test/Tiltfile.test
need this so that the CI tests in https://github.com/tilt-dev/tilt-example-nodejs/pull/12 actually do anything useful
> tests: add run_all param for js tests

- file_sync_only/Tiltfile
- file_sync_only/test/Tiltfile
improve file_sync_only extension (https://github.com/tilt-dev/tilt-extensions/pull/77).
* remove "grep" commands by using read_yaml_stream() or decode_yaml_stream().
* fix resource dependency bugs
* in old version: use image name
* in new version: use k8s resource name related the specified image
* add allow_duplicates option
> fix: imporove file_sync_only extension

- tests/golang/test/fake_project/slow/slow_test.go
This failed in CI thus:
```
Tilt analytics disabled: Environment variable CI=true
Initial Build • (Tiltfile)
Beginning Tiltfile execution
Successfully loaded Tiltfile (50.222921ms)
timeout │ 
timeout │ Initial Build • timeout
timeout │ STEP 1/1 — Running command: [sh -c go test   -timeout 1ms  ./fake_project/slow] (in "/tmp/tmp.1umcuVhG0e/tests/golang/test")
timeout │ ok  	_/tmp/tmp.1umcuVhG0e/tests/golang/test/fake_project/slow	0.037s
timeout │      Step 1 - 0.00s (Running command: [sh -c go test   -timeout 1ms  ./fake_project/slow] (in "/tmp/tmp.1umcuVhG0e/tests/golang/test"))
timeout │      DONE IN: 0.55s 
timeout │ 
timeout │ 
SUCCESS. All workloads are healthy.
+ msg_and_exit 'Expected '\''tilt ci'\'' to fail, but succeeded.'
+ echo 'Expected '\''tilt ci'\'' to fail, but succeeded.' …
```
> extensions: fix timeout test

- restart_process/README.md
- restart_process/Tiltfile
The restart_process extension previously ran into trouble when handling Dockerfiles with non-root users: such a DF wouldn't be able to `touch /.restart-proc` (the default file used to signal a process restart) -- see #52
We worked around this with #62: regardless of the user in the initial Dockerfile, set the user to `root` so we're sure to have permissions for `/.restart-proc`.
This worked okay, but was still a pain for ppl who wanted their subsequent live updates to be run with the user set in their Dockerfile rather than as root (see #98). We even had a user-submitted fix (#162) -- which would cause other, different problems, because presumably live updates as the original non-root user wouldn't have permissions on the `/.restart-proc` file created as `root`.
Rather than increasingly …
> restart_process: solve prob with permissions on restart file by just moving the restart file

- restart_process/tilt-restart-wrapper.go
this will fix [these tests failures](https://app.circleci.com/pipelines/github/tilt-dev/tilt/7270/workflows/8633c63b-2a7e-4990-9d1b-91d962c5e093/jobs/62876) in https://github.com/tilt-dev/tilt/pull/4497 sobbb
> restart_process: run goimports so we can import this into tilt without linter complaining

- cert_manager/README.md
- cert_manager/Tiltfile
Fixes kubernetes-sigs/cluster-api#4559
In using the cert_manager extension, the final test certificate step often fails with this error:
```
Beginning Tiltfile execution
Installing cert-manager
Waiting for cert-manager to start
Testing cert-manager
Traceback (most recent call last):
/Users/matt/Projects/src/sigs.k8s.io/cluster-api-provider-azure/Tiltfile:339:24: in <toplevel>
/Users/matt/Projects/src/sigs.k8s.io/cluster-api-provider-azure/tilt_modules/cert_manager/Tiltfile:61:10: in deploy_cert_manager
<builtin>: in local
Error: command ["sh" "-c" "cat << EOF | kubectl apply -f - \napiVersion: v1\nkind: Namespace\nmetadata:\n  name: cert-manager-test\n---\napiVersion: cert-manager.io/v1\nkind: Issuer\nmetadata:\n  name: test-selfsigned\n  namespace: cert-manager-test\nspec:\n  selfSigned: …
```
> cert_manager: retry creating test certificate for 90s

- coreos_prometheus/Tiltfile
Avoid downloading to the final target directory, using move and clean up
of previous attempts to ensure a final consistent result.
Ensure that files added via listdir are watched which is only enabled
when recursive is enabled.
Move the creation of the cache dir to the set up and retrieval of the
cache path itself and allow for parent components not to exist.
> Improve consistency of final state of coreos prometheus

- uibutton/README.md
- uibutton/Tiltfile
- uibutton/test/Tiltfile
- uibutton/test/test.sh
Extension to make creating custom `UIButton`s for a particular
resource that run a `Cmd` on click easier.
```python
load('ext://uibutton', 'cmd_button')
cmd_button(name='Hello World',
resource='my-resource',
argv=['echo', 'Hello World'])
```
~~(⚠️ Draft until next Tilt release as this will fail tests since the API isn't fully live yet)~~
> uibutton: add extension for Cmd buttons [ch12082]

- .circleci/Dockerfile
Reverts tilt-dev/tilt-extensions#185
See #186 - need to resolve some other issues
> Revert "ci: update to Go 1.16 and ko 0.8.3"

- configmap/README.md
- configmap/Tiltfile
- configmap/test/Tiltfile
- configmap/test/job.yaml
- configmap/test/my-job.env
I ran into a local development use-case where being able to leverage kubectl from-env-file support within config map generation became very relevant. I have made the updates and extended docs and testing suite to support this updated functionality. The main gotcha with the env file loader is that it supports a singular string instead of a list of strings. This is primarily to mitigate confusion with kubectl's behavior of only loading the last provided env file when it has been provided a list of files.
> configmap: Add envfile support

- coreos_prometheus/Tiltfile
- test.sh
* Fix logic to find root Tiltfile (it would just recurse up to
filesystem root)
* Ensure we always try to create cache dir
* Use GitHub release download URL (this is faster and helps solve
issues with tarfile structure)
* Use a cross-platform tar command (possible since the pattern
is now predictable as it doesn't have a Git commit hash but the
tag name instead)
* Suppress most command echo for init process
* Only output on error for download via curl
* Run test as part of CI
Fixes #130.
> coreos_prometheus: cross-platform support + misc fixes

- .circleci/Dockerfile
- .circleci/config.yml
With #186 I forgot to un-revert #185 so the `Dockerfile` was out of sync with what we were actually using making updating it impossible.
This brings back the Dockerfile changes and updates the CircleCI config to use the latest pinned version using those changes (Go 1.16) + Tilt v0.21.1 (latest as of July 6), i.e. this PR's CI will run against the changes included in this PR 😓 .
> ci: fix Dockerfile and update CI image

- configmap/README.md
- configmap/Tiltfile
- configmap/test/Tiltfile
Hi all!
We're big fans of this extension at my company. Internally, we've found it handy to be able to leverage the `--from-literal` option on the same command. This change adds a new function to make that option accessible through the module. 
Thanks!
> Allow configmap extension to use from-literal

- syncback/krsync.sh
Fixes #209
The [shellcheck PR](#206) [quoted `$namespace` in syncback's krsync.sh](https://github.com/tilt-dev/tilt-extensions/commit/018a67d9a544f9f1df6238074db9e781ef7af60b#diff-1735f7dcd2160cebc05a56e9882d2092d4725f9b8104ea5a22e7b81e7fb85864L43). It turns out `$namespace` is not a namespace but either `''` or `'-n some_namespace'`. Quoting the latter breaks the script, yielding this error:
```
error: pod, type/name or --filename must be specified
```
Use the syntax described in the [exceptions section for SC2086](https://github.com/koalaman/shellcheck/wiki/SC2086#exceptions).
I skimmed the [shellcheck PR](#206) and didn't see any other instances of this issue.
> syncback: fix namespace escaping

- workflow/exec_workflow.sh
Use `eval` on the command that is grabbed from the list of commands.
NOTE: The current approach actually has issues with multiline commands;
this is neither fixed nor exacerbated by this change - this is purely
to make shellcheck happy.
> workflow: fix shellcheck violation

- git_resource/Tiltfile
- git_resource/test/Tiltfile
Replace `local('basename ...') with `os.path.basename()` so that
it's portable across platforms without needing GNU coreutils.
Fixes #211.
> git_resource: add Windows support

- git_resource/Tiltfile
When the repo has already been cloned, the extension checks for
local modifications using output from `git status` and seeing if
there are any lines using `wc -l`. This isn't portable to Windows,
and trying to use hacks with `find /c /v ""` produce weird errors,
so just do the line counting in Starlark.
Additionally, use `os.path.join` consistently instead of manually
concatenating strings with `/` to make Windows tools happy.
Fixes #211.
> git_resource: additional portability fixes

- .circleci/config.yml
Something between GitHub and CircleCI means the jobs were just
getting considered by the final part of the name, so `check` (our
custom Tilt extensions validation) and `shellcheck/check` (from
the orb) were clobbering each other - GitHub would only show
2 checks (there are 3) and so shellcheck failures could be
hidden.
Easy fix here is to just rename one of the jobs 🤷
> ci: make shellcheck violations visible in GitHub UI

- local_output/Tiltfile
This extension is super handy for grabbing the output of commands, but it doesn't have argument parity with the builtin `local`. It's often super handy to be able to pass in a new env var or set `quiet`, this PR adds the same default args as `local` and passes them through
> Accept all local args in local_output

- restart_process/Tiltfile
- restart_process/test/test-docker.sh
- restart_process/tilt-restart-wrapper.go
Please review the following commits I made in branch nicks/restart2:
cdeceebc29b3ac66cf6e448d63ff2dbe78427cf4 (2021-08-09 16:52:25 -0400)
restart_process: Create restart-wrapper container image with custom entr args
> restart_process: Create restart-wrapper container image with custom entr args

- .circleci/config.yml
- Makefile
- test.sh
1. no longer require explicitly adding test.sh scripts to the root test.sh
2. use `make shellcheck` instead of the circleci shellcheck orb:
a. it was failing due to https://github.com/CircleCI-Public/shellcheck-orb/issues/42
b. it seems nice to avoid divergence between ci and `make shellcheck` (e.g., `make shellcheck` excludes the ".git-resources" directory and passes "-e SC2001", but AFAICT the shellcheck job does not)
> extensions: find/run all test.sh scripts rather than listing explicitly

- .gitignore
- workflow/README.md
- workflow/Tiltfile
- workflow/exec_reset.sh
- workflow/exec_workflow.sh
- workflow/increment_index.sh
- workflow/write_index.sh
- workflow/write_reset.sh
- workflow/write_workflow.sh
Some miscellaneous changes based on (small) hiccups I encountered when using this for the workshop.
I bundled these together just because it was easier and they are pretty small tweaks.
* adjust button labels to be a bit more user friendly / "pretty"
* only reset progress on initial load
* realized whenever you make a change to `Tiltfile` or any other "config" files, it'd reset you back to beginning
* store temporary files in the `tilt_modules/workflow` directory to avoid creating a bunch of temp files in the repo root
* undocumented `TILT_WORKFLOW_STATE_PATH` env var can allow setting a custom directory (e.g. tmpdir)
* make sure all temp files meet pattern `workflow_*.tmp` to make it easy to `.gitignore` them
* see above: hopefully most people already ignore `tilt_modules/` so won't need …
> workflow: quality of life tweaks

- helm_remote/Tiltfile
This redirected to stdout on error (such as when no repos were found) which meant that rather than the `|| ver/nul` getting returned, you'd get something like `{"Error": "no repositories to show"}` on stdout which breaks the list comprehension on the next line (note: Helm returns a different error the first time it is run with no repos compared to when you remove all repos- then the command returns an empty list instead).
> Helm Remote Extension - Redirect stderr to nul on Windows

- secret/Tiltfile
- secret/test/Tiltfile
- secret/test/job.yaml
- secret/test/test.sh
I am currently using Tilt to develop configuration for backstage.
Backstage required Gihtub credentials so I ended up with this;
```
k8s_yaml(secret_from_dict("github", inputs = {
'AUTH_GITHUB_CLIENT_ID'     : os.getenv("AUTH_GITHUB_CLIENT_ID"),
'AUTH_GITHUB_CLIENT_SECRET' : os.getenv("AUTH_GITHUB_CLIENT_SECRET")
}))
```
and the proposed function based on the `configmap` extension,
> secret: function to generate secret config from a map

- .gitattributes
CRLF line-endings break the ability to execute shell scripts on Windows. This will allow extensions that rely on shell scripts (like Syncback) greater compatibility with Windows/WSL.
> Maintain LF line-endings for shell scripts on Windows systems

- secret/README.md
Hello @nicks,
Please review the following commits I made in branch nicks/readme:
2741af7da2c24d6c9e399d4a1833cfd0489b727d (2021-09-02 17:04:10 -0400)
secret: add secret_from_dict to the readme
> secret: add secret_from_dict to the readme

- kubefwd/README.md
- kubefwd/Tiltfile
- kubefwd/watch-namespaces.sh
Please review the following commits I made in branch nicks/readonly:
11ef9ebde5038a71bd37c5eb3f58bd5355f09666 (2021-09-08 18:58:41 -0400)
kubefwd: add the ability to kubefwd a namespace we don't deploy to
2741af7da2c24d6c9e399d4a1833cfd0489b727d (2021-09-02 17:04:10 -0400)
secret: add secret_from_dict to the readme
> kubefwd: add the ability to kubefwd a namespace we don't deploy to

- README.md
- kim/README.md
- kim/Tiltfile
Hi,
Very simple extension that allows you to build images using kim https://github.com/rancher/kim 
Opens up support for running Tilt against Rancher Desktop https://github.com/rancher-sandbox/rancher-desktop and without having docker installed.
I was having some trouble with my local registry, so I've disabled the `kim push $EXPECTED_REF` command for now, as kim automatically pushes the image into the cluster.
Let me know what you think.
/Lasse
> kim: add extension to build images using kim.

- namespace/README.md
- namespace/Tiltfile
This commit adds optional parameters to the namespace functions to set labels and annotations at namespace creation time. If either parameter is not set, the corresponding section is excluded from the yaml.
> namespace Add labels and annotation options to namespace_create and namespace_yaml

- README.md
- tarfetch/README.md
- tarfetch/Tiltfile
I wrote this extension after spending a few days working through multiple challenges related to using syncback on Windows. While this extension is not as full-featured as the rsync-based syncback extension, it serves my purposes and those of my co-workers well enough in retrieving new and changed files from Kubernetes containers.
I am not too attached to the name, formatting (I tried to adhere to Black formatting), etc. and am open to critique should anything need changed or refined.
I hope this can help others as much as it is helping me.
> tarfetch: new tilt extension for reverse sync from containers

- ngrok/README.md
- ngrok/Tiltfile
- ngrok/ngrok-reconcile-config.sh
Please review the following commits I made in branch nicks/password:
00e077c02543919865ba7374301d6e9669698ef4 (2021-09-10 20:08:45 -0400)
ngrok: add support for basic auth
dd96e9988399c4eb6e4b9b36f83069ee694ba35e (2021-09-10 18:35:45 -0400)
ngrok: add an ngrok operator
> ngrok: add support for basic auth

- .circleci/config.yml
After a bad change the other day, CI got stuck running tests for
~3 hours before I noticed.
CircleCI doesn't have a generic timeout option in YAML config,
they recommend using the `timeout` command if not using a test
framework that already supports a specific option.
As of June 2021, tests take ~7m to run in CI, so this gives a
big buffer by capping at 15m at which point it'll send `SIGTERM`.
If the tests don't shut down cleanly after another minute, it'll
send a `SIGKILL`.
> ci: add timeout to test execution

- README.md
- nix/README.md
- nix/Tiltfile
- nix/test/Tiltfile
- nix/test/deployment.yaml
- nix/test/nix/image.nix
- nix/test/test.sh
Added function to build images with nix.
I used `sed` to extract image-name from `docker load`, it kindof relies on docker not changing output from `docker load`.
Without that part, user would have to pass in the full name of the docker image  being created by nix.
Which is optional in nix, you dont have to supply a name, which will cause it to have autogenerated name.
So its nice if we can capture it, and not sure if there is a better way.
> nix: added build_nix_image

- .circleci/Dockerfile
- .circleci/config.yml
- README.md
Hello @nicks,
Please review the following commits I made in branch nicks/kubectlbuild:
ab698efd55daa7680a3685bea898f49f7872b564 (2021-11-04 12:38:47 -0400)
circleci: update ci image to go 1.17
> circleci: update ci image to go 1.17

- kubectl_build/Tiltfile
While using the `kubectl_build` extension, I was unable to pass in build arguments. It appears that docker expects `key=value` as a single string.
The current output is the following and is failing.
`--build-arg mykey= myvalue` <-- note the space after the equal operator
Correct parameter to be passed in should look like so.
`--build-arg mykey=myvalue`
This has been tested successfully in my local environment.
> Value from build arg dictionary should join as single string

- README.md
Example solution for: https://github.com/tilt-dev/tilt-extensions/issues/287
I think it should be easy to find the docs on any function I can call in a Tiltfile.
> Enhance docs docker restart

- nix/Tiltfile
Noticed some issues with the previous extraction of `$IMG_NAME` from `docker load`.
The stdout filtering/sed only worked when the image had been previously loaded, because then the stdout only contained a single line, otherwise docker printed multiple lines to stdout, so `$IMG_NAME` var got multiple lines, which resulted in the tagging process not working.
Now I use `-n` which suppress automatic printing of pattern space.
Then append `p` which prints the current pattern space, which results in only printint output from matching line.
> nix: fix sed expression

- nix/Tiltfile
- get tag from `manifest.json` inside `tar.gz` instead of `docker load` stdout.
- `set -e` to have commands fail early to get easier to read errors.
- `--no-out-link` so the built `.tar.gz` will be collected by nix garbage collector.
After tips from https://github.com/tilt-dev/tilt-extensions/pull/292#pullrequestreview-803039132
> nix: get tag from manifest.json

- honeycomb/events.py
Hello @landism, @nicksieger,
Please review the following commits I made in branch nicks/honeycomb3:
20b2fcd17de4b7abe3c579c45e725fa8b0fceeaa (2021-12-06 17:55:37 -0500)
honeycomb: report event at start rather than end
> honeycomb: report event at start rather than end

- docker_build_sub/Tiltfile
- docker_build_sub/test/Dockerfile
- docker_build_sub/test/Tiltfile
- docker_build_sub/test/deployment.yaml
- docker_build_sub/test/index.html
- docker_build_sub/test/main.sh
- docker_build_sub/test/test.sh
Please review the following commits I made in branch nicks/sub:
407ac02c090f56b6237c9d8a5ee55640f1f8e552 (2021-12-10 09:49:02 -0500)
docker_build_sub: handle the dockerfile= argument correctly
see this report for more info: https://github.com/tilt-dev/tilt-extensions/pull/304
> docker_build_sub: handle the dockerfile= argument correctly

- kubefwd/Tiltfile
- ngrok/Tiltfile
BSD `mktemp` has some differences compared to the GNU variant,
so this is the most portable way to make temporary files that
works across macOS + Linux that I could find. Note that the ngrok
file won't end in `.yml` anymore because BSD `mktemp` only allows
the randomized part of the template (i.e. `XXXXXX`) to be at the
END of the filename.
Both of these assume a POSIX-y env as-is (e.g. they're running
Bash scripts for their main operator functionality, so no attempt
at supporting Windows cmd is made here.
> kubefwd/ngrok: use portable mktemp invocation for macOS/Linux

- ngrok/ngrok-run.sh
Another small BSD vs GNU thing: `wc` prepends some spaces on the
BSD/macOS version:
```
$ wc -l "$config_file"
0 /var/folders/r2/12r1dtqn2zqc4yg_kfnprfv80000gn/T//tilt-ngrok.y8z4hmDGs
```
Using `awk` works with both variations.
(Another variation would be `wc -l < "$config_file" | xargs` since
`wc` won't print the filename if reading from stdin and `xargs` trims
stuff, but that's a bit obtuse and abusing `xargs` IMO.)
I found this while verifying my `mktemp` fix (#312).
> ngrok: fix error with no tunnels on macOS

- honeycomb/test/events_test.py
Hello @nicks,
Please review the following commits I made in branch nicks/honeycomb2:
da28f1675f86c3d5317136e5fa5eb2bc3214052e (2021-12-21 11:30:04 -0500)
honeycomb: make the test wait a bit on the apiserver
> honeycomb: make the test wait a bit on the apiserver

- tests/golang/Tiltfile
- tests/javascript/Tiltfile
Hello @lizzthabet, @landism,
Please review the following commits I made in branch nicks/tests2:
a3401cc36b68c870e10b4e9680246eaab22442e3 (2022-01-04 18:20:06 -0500)
tests: use local_resource instead of the test() built-in
> tests: use local_resource instead of the test() built-in

- syncback/Tiltfile
- syncback/test/Tiltfile
- syncback/test/test.sh
Allows installing syncback as a `cmd_button` in coordination with the `uibutton`
extension instead of as a local resource.
Example:
```starlark
load('ext://uibutton', 'cmd_button')
load('ext://syncback' 'syncback_command_args')
docker_build('myapp', './app')
k8s_yaml('app.yaml')
k8s_resource('myapp', port_forwards=[5000])
cmd_button('Sync', 'myapp', syncback_command_args('deploy/myapp', '/app'))
```
> syncback: extract syncback_command_args and syncback_command helpers

- uibutton/Tiltfile
- uibutton/test/test.sh
Only create buttons for `tilt up` and `tilt ci`. Other commands,
such as `tilt alpha tiltfile-result`, load the Tiltfile but do NOT
launch the apiserver, so buttons can't be created.
> uibutton: fix errors running some commands

- color/README.md
- color/Tiltfile
- color/test/Tiltfile
- color/test/test.sh
Add ANSI color codes to your Tiltfile log messages.
Works with Tiltfile built-ins such as `print`, `warn`, `fail`, `exit`
in addition to custom functions.
> color: add extension for ANSI codes in Tiltfile

- helm_resource/Tiltfile
Old versions of BSD `sed` don't include the `-r` flag for extended
regex (they instead use `-E`). This prevents things from working
on older macOS versions (e.g. 10.15).
Use `-e` instead for greater portability, which works fine for our
regexes with a slight extra escape on the capture group for BRE
compatibility.
Fixes #328.
> helm_resource: fix sed errors on old macOS

- secret/Tiltfile
Being that secrets generally contain sensitive keys, this PR adds an option to various methods within the `secret` extension where users will have the option to prevent secret creation from exposing keys in Tilt's UI/logging console.
Default option is set to `False` as the use case may not apply to all.
> Add echo option to prevent secrets from printing to stdout

- knative/Tiltfile
The current code chokes if `last-applied-configuration` is present:
```
kubectl get configmap -n kube-public local-registry-hosting -oyaml                                                                              
apiVersion: v1
data:
localRegistryHosting.v1: |
host: localhost:55547
hostFromClusterNetwork: k3d-runhub-registry:5000
hostFromContainerRuntime: k3d-runhub-registry:5000
help: https://k3d.io/usage/guides/registries/#using-a-local-registry
kind: ConfigMap
metadata:
annotations:
kubectl.kubernetes.io/last-applied-configuration: |
{"apiVersion":"v1","data":{"localRegistryHosting.v1":"host: localhost:55547\nhostFromClusterNetwork: k3d-runhub-registry:5000\nhostFromContainerRuntime: k3d-runhub-registry:5000\nhelp: https://k3d.io/usage/guides/registries/#using-a-local-registry\n"}," …
```
> knative: fix local registry host parsing

- git_resource/Tiltfile
- helm_remote/Tiltfile
For windows compatibility. Fixes #339.
> helm_remote/git_resource: use command list instead of shell escaping

- .circleci/config.yml
- tilt_inspector/Tiltfile
Hello @nicks,
Please review the following commits I made in branch nicks/space:
f158d9e6f9b5facf07c866d95d1409a3f178c49a (2022-02-17 19:12:02 -0500)
circleci: add a space to the ci working dir
> circleci: add a space to the ci working dir

- kim/README.md
- nerdctl/README.md
- nerdctl/Tiltfile
- nerdctl/test/Dockerfile
- nerdctl/test/Tiltfile
- nerdctl/test/deployment.yaml
- nerdctl/test/index.html
- nerdctl/test/main.sh
- nerdctl/test/test.sh
- test.sh
This is primarily useful for Rancher Desktop users at the moment
and supersedes the `kim` extension.
> nerdctl: extension for containerd in-cluster builds

- syncback/krsync.sh
Syncback tests are failing for me on master without these changes; not sure why
they are succeeding in CircleCI.
> syncback: improve in-container rsync detection

- syncback/README.md
- syncback/Tiltfile
- syncback/test/Tiltfile
- syncback/test/test.sh
- Fix paths not being properly applied
- syncback: use `paths` in test
- syncback: fix use of paths/include/exclude
> syncback: fix paths/include/exclude behavior

- helm_resource/README.md
- helm_resource/Tiltfile
We have an API server running using tilt that we wish to communicate with. The server listens on a specific port but the underlying `k8s_resource()` does not let us specify a port meaning that when we send requests we don't know which port to send them to. 
By adding the `port_forwards` argument we can optionally set the port on the `k8s_resource` function so we know to which port we can send requests to the server.
> helm_resource: Add port_forwards parameter for underlying k8s_resource

- pack/test/Tiltfile
Hello @nicks,
Please review the following commits I made in branch nicks/pack2:
1dd2bc92c7eea2331cb1ab0ed5e66b1e258da13e (2022-03-18 17:55:33 -0400)
test: pin httpd 0.2.2 in the pack test
see:
https://github.com/paketo-buildpacks/httpd/issues/297
> test: pin httpd 0.2.2 in the pack test

- nerdctl/Tiltfile
Currently on windows this fails with 
```
error: failed to solve: failed to parse %example-nerdctl-image:tilt-build-1648718547%: invalid reference format
```
My suggestion is to use format to avoid single `%E` looking odd in code syntax.
Tested locally with `tilt ci`
```
[event: pod example-nerdctl-6464d5ddb4-zljd7] Container image "example-nerdctl-image:tilt-build-1648718665" already present on machine
SUCCESS. All workloads are healthy.
```
> fix: double percentage escape for nerdctl build

- .circleci/config.yml
Hello @nicks,
Please review the following commits I made in branch nicks/dockerversion:
c6c3156a4cb398ddfbb6feb4f4e12f45278019fe (2022-04-06 17:41:52 -0400)
ci: bump remote docker version
> ci: bump remote docker version

- pulumi/test/Pulumi.dev.yaml
- pulumi/test/test.sh
Hello @nicks,
Please review the following commits I made in branch nicks/pulumi3:
a9f13f8c0ccd71912b8ec7564b393a68b7735825 (2022-04-06 17:57:17 -0400)
test: disable pulumi test if no pulumi user
> test: disable pulumi test if no pulumi user

- docker_build_sub/Tiltfile
With parent as a multi-part dockerfile, it is often useful to build with a dockerfile target. This target should not be passed down to child dockerfile build, as it will always fail with the selected target stage not being available to child.
> Fix issue with multi-part target in child build parameters

- min_k8s_version/Tiltfile
A friend of mine is using Windows and had no `grep` installed.
> min_k8s_version: remove 'grep' and use a native way

- kubefwd/sudo-kubefwd.sh
Based on @nicks' suggestion for #368, this PR follows the pattern in the [`syncback` extension](https://github.com/tilt-dev/tilt-extensions/blob/master/syncback/krsync.sh#L15-L21), which copies scripts to a `tmp` directory before running them.
I'm on MacOS, so I tested these changes by moving the extension `Tiltfile` into a parent directory with a space in its name. Without the changes, the kubefwd scripts fail and with them, they run successfully.
I'm not very familiar with this extension, so feel free to chime in with any technical / style suggestions!
> kubefwd: copy `run_kubefwd` scripts into a new directory to avoid path normalization issues

- uibutton/Tiltfile
Some windows users have reported that getting the timestamp (which we do to set the StartAfter field) can take seconds. That's annoyingly slow by itself, but we do it once per button, which makes it even worse.
Only get the timestamp once per Tiltfile execution and use it for all uibuttons.
It'd still be good to add a native timestamp function to avoid shelling out, but that requires a Tilt release and raise the minimum required Tilt version for this extension, so we might as well do this as a short-term mitigation.
> uibutton: only get timestamp once per run

- helm_resource/helm-apply-helper.py
- helm_resource/test/helloworld/templates/configmaps.yaml
Please review the following commits I made in branch nicks/bug:
534eea26eaf763802fe6d412cfb487ddeed4e0b2 (2022-04-15 13:20:33 -0400)
helm_resource: default our own namespaces, trying again
fixes https://github.com/tilt-dev/tilt-extensions/issues/379
fixes https://github.com/tilt-dev/tilt-extensions/issues/374
> helm_resource: default our own namespaces, trying again

- helm_resource/README.md
- helm_resource/Tiltfile
- helm_resource/helm-apply-helper.py
- helm_resource/test/Tiltfile
- helm_resource/test/helloregistry/.helmignore
- helm_resource/test/helloregistry/Chart.yaml
- helm_resource/test/helloregistry/templates/NOTES.txt
- helm_resource/test/helloregistry/templates/_helpers.tpl
- helm_resource/test/helloregistry/templates/configmaps.yaml
- helm_resource/test/helloregistry/templates/deployment.yaml
- helm_resource/test/helloregistry/templates/hpa.yaml
- helm_resource/test/helloregistry/templates/ingress.yaml
- helm_resource/test/helloregistry/templates/service.yaml
- helm_resource/test/helloregistry/templates/serviceaccount.yaml
- helm_resource/test/helloregistry/templates/tests/test-connection.yaml
- helm_resource/test/helloregistry/values.yaml
Currently the `helm_resource` extension supports passing image references to charts either as a single string or as a tuple that maps to two fields in a values file (the default created by `helm create`). This PR adds support for an additional type of structure that uses three fields in a values file:
```yaml
image:
registry: docker.io
repository: foo/bar
tag: 1.0.0
```
A second chart has been added to test this scenario and the test `Tiltfile` has been updated to deploy both simultaneously so as to ensure backwards compatibility with the previous tuple functionality.
> helm_resource: Add support for charts that use three fields for passing image references

- k8s_attach/Tiltfile
As list.append https://github.com/bazelbuild/starlark/blob/master/spec.md#list%C2%B7append
seem to only take 1 arg.
> k8s_attach: namespace arg works

- restart_process/Tiltfile
Makes the extension friendlier to people running with setups where the runtime
user is not root.
> restart_process: chmod 666 on restart file

- pack/Tiltfile
Currently the pack extension always sets `BP_LIVE_RELOAD_ENABLED` to `true`.
There are some common [Buildpacks builders](https://github.com/paketo-buildpacks/tiny-builder) which are not compatible with `watchexec`, which is [expected by this flag](https://paketo.io/docs/howto/python/#enable-process-reloading).
This extension will error if trying to build with one of these buildpacks e.g. 
This PR allows the user to provide the `BP_LIVE_RELOAD_ENABLED` flag.  If the flag is provided by the user, e.g. `BP_LIVE_RELOAD_ENABLED=false`, the extension will no longer try to overwrite or append a duplicate, conflicting flag.
> Pack - allow `BP_LIVE_RELOAD_ENABLED` to be set by the user

- .circleci/Dockerfile
- .circleci/config.yml
- Makefile
Please review the following commits I made in branch nicks/images:
45e3330d1e1653e4b6495183313db7fa017f9c4b (2022-06-10 15:01:39 -0400)
circleci: move images to docker org
> circleci: move images to docker org

- helm_resource/helm-apply-helper.py
Make `helm_resource()` pass its namespace parameter to the `kubectl` command, not just the `helm` command.
This fixes a bug where deploying a new service into a custom namespace would fail on the `kubectl get -oyaml -` step.  `helm_resource()` calls to Helm use `helm --namespace SOME_NAME` to work on a specific namespace. `helm_resource()` calls to `kubectl` would look in the default namespace for the resources that Helm just created in the custom namespace, causing `kubectl` to return an error code.
> helm_resource: fix helm_resource() so it will deploy to custom namespaces

- secret/README.md
- secret/Tiltfile
In order to perform an operation like this kubectl command:
```
kubectl create secret docker-registry artifact-registry \
--docker-server=host.somedomain \
--docker-username=_json_key \
--docker-password="$(cat service-account.json)" \
--docker-email=email@email.com
```
This does not work with `secret_yaml_generic()` or `secret_from_dict()`
I have created a new function for this, that will hopefully make creating these secrets easier for others: `registry_secret()`
```
name: The configmap name.
namespace: The namespace.
inputs: A dict of keys and values to use. Nesting is not supported
flags_dict (optional): the flags used by docker-registry secret command
Example: '{"docker_server": "host", "docker_username": "username", "docker-password": "password", "docker_email": "email@email.com"}' …
```
> Add secret type to secret_from_dict()

- earthly/README.md
- earthly/Tiltfile
- earthly/test/Tiltfile.restart
- earthly/test/test.sh
Turns out that for windows-native earthly installations the `$EXPECTED_REF` variable was not expanded properly.
Needed to add a windows-specific command via `command_bat`.
Additionally, I added a "docker_build_with_restart"-like functionality.
> earthly: add windows-specific command and restarts

- .gitignore
- helm_remote/test/Tiltfile
Hello @nicks,
Please review the following commits I made in branch nicks/helm_remote:
6afe913a6c2b3b9c91b2c3f518c30eef01358c90 (2022-07-08 18:40:15 -0400)
test: remove the helm_remote/gloo tests
the chart is failing to install. i think this is a problem
with the underlying chart, now with anything tilt is doing.
> test: remove the helm_remote/gloo tests

- uibutton/README.md
- uibutton/Tiltfile
- uibutton/test/Tiltfile
Hi all,
We've encountered use cases for having disabled buttons, as well as buttons that require confirmation (e.g. destructive actions), and we noticed that those features are supported by Tilt. However, the uibutton extension doesn't expose those params. We tested those changes in our Tiltfile and felt like it would be a quick win to share this to the main repo.
Let me know what you think!
> Expose disabled and requires_confirmation for uibutton extension

- kubectl_build/README.md
- kubectl_build/Tiltfile
Adding `push` as an optional parameter to `kubectl_build` that appends the `--push` argument to the `kubectl build` command line. This defaults to `False`, maintaining the existing behavior.
When using an external registry with Tilt, the images built by `kubectl_build` must be pushed to the registry in order to be pulled and started by tilt. This is handled by the `kubectl build` command, but needs to be exposed to the corresponding tilt function.
> Add support for kubectl_build `--push` argument

- kubectl_build/Tiltfile
Add kubectl_build builder options `namespace` and `builder`, corresponding to `kubectl-build` command line options `--namespace` and `--builder`. These options are used by `kubectl-build` to locate the builder pod to be used.
These options allow the builder pod to be located in a common namespace colocated with the registry secret.
> Additional kubectl_build options

- knative/Tiltfile
In ubuntu microk8s patching configmap/config-deployment with local registry failed. The Tilt console showed a double quote after substituting $REGISTRY inside the patch command
this fixed the issue in my machine
> double quotes in extracted local registry -> Error from server (BadRequest): Invalid JSON Patch

- ngrok/README.md
- ngrok/Tiltfile
- ngrok/ngrok-reconcile-config.sh
Adding `--ngrok_config_tls_scheme` as an arg with a value of `https` will create https tunnels instead of http ones.
> feat: Add flag to configure tls scheme used by tunnels

- namespace/test/job-default-namespace.yaml
- namespace/test/job.yaml
the test has gotten more flaky recently...
i wonder if job scheduling has just gotten faster, and so sometimes the test fails because dns isn't ready yet.
> add retries to namespace test

- helm_remote/Tiltfile
This PR introduces support for OCI registries like ECR to the helm_remote plugin. This fixes #457 
The only changes needed are to allow urls in the `repo_name` field and replace `helm search` with `helm show`.
https://helm.sh/docs/topics/registries/
Example:
```
helm_remote(
'chart-name',
repo_name='oci://835442211234.dkr.ecr.eu-west-1.amazonaws.com',
release_name='my-namespace',
values=['{}/values.yaml'.format(os.path.dirname(__file__))],
)
```
> Support OCI helm registries

- execute_in_pod/README.md
- execute_in_pod/Tiltfile
I've tried on a project again the newly merged:
- https://github.com/tilt-dev/tilt-extensions/pull/459
It seems to have some issues that I wasn't having before as it worked correctly for me, as it is currently not working I modified it to have a dumbed down version of it working (without checks on pods/containers....)
I'm not sure why the past 1-2~ weeks was working for me and suddenly I'm not able to have it working again 🙃 (I do wonder if was a special state in my machine) and I guess that's why having the ci tests would have been a good idea!
It will need more work to figure out that I currently won't be able to dedicate due to vacations so please either accept the dumbed down version as it works (tested again from scratch, no possibility of specifying a container nor it will check …
> temporarely dumb down execute in pod

- helm_resource/README.md
- helm_resource/Tiltfile
Include support for the `auto_init` keyword argument from [`k8s_resource`][0].
The use-case is our team wants to be able to run a service from a Helm chart in our cluster, but it is not critical to the functionality of the cluster and incurs a significant performance cost. We would like to be able opt-out of starting this heavy service automatically when running `tilt up`.
No tests are included because I'm not certain how to test that a resource _doesn't_ exist in a meaningful way.
[0]: https://docs.tilt.dev/api.html#api.k8s_resource
> helm_resource: Add `auto_init` keyword argument

- github_token/README.md
- github_token/Tiltfile
- github_token/test/Tiltfile
Extracting from an internal project Tiltfile to make it easy to use in multiple projects where a GitHub PAT secret is needed.
> github_token: new extension to retrieve GitHub PAT with GH CLI

- github_token/Tiltfile
Since Tilt `local` doesn't allow catching non-zero exit codes, force them to
zero so we can display a helpful error message.
Signed-off-by: Nick Sieger <nick@nicksieger.com>
> github_token: fix non-zero exit codes

- syncback/Tiltfile
- syncback/krsync.sh
Adds functionality to customize the rsync path on the container to resolve potential permission errors if the execution user does not have permission to modify the containers `/bin` directory. Resolves https://github.com/tilt-dev/tilt-extensions/issues/478
Adds the `tilt_rsync_path` parameter to the `syncback` command.
Used like:
```
syncback("python-syncback", 
"deploy/syncback-containers", 
"/root/", 
paths=['main.py'],  
target_dir=python, 
container="python", 
namespace="syncback-test",
rsync_path="/some/remote/path/"
)
```
> [Feature] Add rsync tilt path

- helm_resource/helm-delete-helper.py
- helm_resource/test/Tiltfile
This PR makes `helm-delete-helper` smarter by checking if a release is installed _before_ trying to uninstall it.
After #471 was merged, it's possible for Helm releases to be known to Tilt, but not actually running in the cluster. This means that when `tilt down` is called, the [`helm uninstall`][0] command run by `helm-delete-helper` will fail with an error like:
> Error: uninstall: Release not loaded: kafka-operator: release: not found
While these errors are harmless, they are noisy and can appear as if Tilt itself is failing. This PR aims to remove those errors altogether by calling [`helm status`][1] first and checking that it was successful before calling `helm uninstall`.
The rest of the code was also refactored to be simpler.
To test this, run the `/helm_resource/tests/test.sh`. …
> helm_resource: Make helm-delete-helper quieter

- kubebuilder/Tiltfile
The default kubebuilder boilerplate includes a security context forbidding root user which is required by Tilt.
This PR adds a `DISABLE_SECURITY_CONTEXT` option, enabled by default to patch the deployment and remove the security context as [this comment](https://github.com/tilt-dev/tilt/issues/3060#issuecomment-779726111).
@jazzdan
> kubebuilder: disable security context

- git_resource/Tiltfile
Currently if you reference a repo with a branch,then change that branch it will fail with an error of 'No such reference'. This is because since version 1.8, Git shallow clones only pull a single branch [1]. There was a flag added (--no-single-branch) to pull all branches.
[1] https://stackoverflow.com/questions/23708231/git-shallow-clone-clone-depth-misses-remote-branches
> git_resource: add no-single-branch flag for shallow clones

- kubectl_build/Tiltfile
This PR adds support for the `--platform` argument when running `kubectl_build`, a standard way to specify build arches supported by both the `docker_build` ext and the underlying Docker CLI.
Crucial component to deploying remotely in variable environments (i.e. clusters running on mixed-arch spot instances).
> kubectl_build: Add support for --platform argument

- README.md
- k8s_yaml_glob/README.md
- k8s_yaml_glob/Tiltfile
A simple extension to facilitate loading subsets of manifests by directory and filename patterns.
First load the extension like:
load('ext://k8s_yaml_glob', 'k8s_yaml_glob')
Then use it like this:
k8s_yaml_glob('./k8s/*.yaml')  
or like this:
k8s_yaml_glob('./k8s/**/dev-*.yaml')
> feat: k8s_yaml_glob extension for loading manifests by glob patterns.

- helm_remote/README.md
- helm_remote/Tiltfile
I have found an issue with one of our Helm charts. 
`Error: chart requires kubeVersion: >=1.21.0-0 which is incompatible with Kubernetes v1.20.0\n\nUse --debug flag to render out invalid YAML`
My Kubernetes version is `1.25.3`, so I suspected `helm`. Here is the solution: https://github.com/helm/helm/issues/10086#issuecomment-909595139
But the case is Tilt built in `helm` function doesn't support validate flag, so this change uses a custom `template` command which optionally validate-able.
> Validate flag for helm_remote extension

- kubectl_build/Tiltfile
https://github.com/vmware-tanzu/buildkit-cli-for-kubectl supports --cache-to, so we want to experiment and see how it behaves for us
I'm brand new to submitting requests to any tilt repos, so by all means point me toward any docs or guidelines I should be following if I'm doing this wrong please :)
> Support --cache-to in kubectl_build

- helm_remote/README.md
- helm_remote/Tiltfile
Reverts tilt-dev/tilt-extensions#504
This introduced a regression such that the `namespace` argument is no longer respected.
Fixes #506.
> Revert "Validate flag for helm_remote extension"

- kubectl_build/Tiltfile
windows is using %EXPECTED_REF% instat of $EXPECTED_REF
> Fix kubectl_build for window

- procfile/Tiltfile
- procfile/test/Procfile
- procfile/test/Procfile.two
- procfile/test/Tiltfile
- procfile/test/test.sh
Hi team,
Small change to allow passing kwargs to local_resource. Enable things like Labels or AutoInit=False on Procfile resources.
I'm not sure how to add tests, if needed. Happy to have some guidances.
Cheers
> feat(procfile): allow passing kwargs to local_resource

- min_k8s_version/Tiltfile
Context:
- kubectl deprecated --short flag for kubectl version at v1.24 https://github.com/kubernetes/kubernetes/pull/108987
- kubectl removed --short flag for kubectl version at v1.28 https://github.com/kubernetes/kubernetes/pull/116720
currently we have an error in the below with kubectl v1.28
default output is changed as same as --short flag
```
Error in local: command "kubectl version --short" failed.
error: exit status 1
stdout: ""
stderr: "error: unknown flag: --short\nSee 'kubectl version --help' for usage.\n"
```
Verified and works with kubectl v1.27 and 1.28 too.
Changes:
We support both versions of k8s by trying first the normal path, and if we get the old output back (that always starts with a version.Info string), then we fall back to the old logic.
This is a less restrictive …
> Fix min version issue with k8s client

- helm_resource/Tiltfile
Fixes an issue where helm_resources pointing to helm charts without pods would never be marked as ready.
> adding `pod_readiness` flag to `helm_resource`

- helm_remote/Tiltfile
previously it would create a target path like
"..\\AppData\\Local\\tilt-dev\\.helm\\oci:\\repo.net:1234\\chart\\latest" which is not a valid path on windows. so now we just strip every :
> helm_remote: fix pulling oci helm charts on windows

- kubebuilder/Tiltfile
Kubebuilder 3.13 puts the go.main in cmd/
> fix(kubebuilder): Update go.main path

- restart_process/Tiltfile
Sometimes the container root filesystem has sticky bit enabled and restart commands are ran with a different user. We can work around that by creating an intermediate folder that has "0777" permissions.
Refs #540
> fix(restart_process): work around sticky /tmp

- nerdctl/Tiltfile
The `nerdctl` extension was not passing through the `platform` argument to the under lying command. 
tested locally with the following example
```
nerdctl_build(
ref='my-docker-image', 
context='.',
platform='amd64'
)
```
output observed in the Tilt UI
```
Running cmd: nerdctl --namespace k8s.io build --platform amd64 -t "${EXPECTED_REF}" .
```
> fix: pass through 'platform' arg to nerdctl

- README.md
- base64/README.md
- base64/Tiltfile
It looks like the PowerShell version strips newlines inside the content, I am not sure it can be avoided. Unless we want to build the function natively, which I think we should.
Closes #538
> Add base64 extension

- .circleci/Dockerfile
- .circleci/config.yml
> circleci: update to go 1.21

- vault_client/README.md
The extension name seem to be `vault_client` instead of `vault_cli`
> `vault_client`: Fix extention name typo in example

- syncback/Tiltfile
This adds a parameter to the syncback extension that allows specifying of any `rsync` options for more advanced usage. Right now I'm using it to work around #567 with the following code:
```python
syncback('sync lockfiles', 'deploy/name-pn', '/rails/', 
rsync_options=[
'--include=db/', '--include=db/schema.rb',
'--include=Gemfile.lock', '--include=yarn.lock', '--exclude=*'
]
)
```
but I imagine it could be used for all kinds of other advanced usage. I'm still up for attempting to write the more user-friendly solution to #567 if that's of interest too.
> Add rsync_options parameter to syncback

- logger/README.md
- logger/Tiltfile
For larger tilt projects with a lot of `print` function usages, it might be useful to have a more readable and colorful text output in the tilt ui. This approach makes things like debugging much easier. This logger is inspired by the [Maven](https://maven.apache.org/) logger.
> logger: add logger extension

- base64/Tiltfile
- the base64 binary on macOS has no "-w" cli option. there is an alternative "-b" which has "0" as default, so we pass "-w 0" only if we are NOT on macOS
- implement local_output module
> base64: fix error on macOS

- helm_resource/README.md
- helm_resource/Tiltfile
This PR adds the `links` argument from [`k8s_resource()`](https://docs.tilt.dev/api#api.k8s_resource) to `helm_resource()` so that clickable URLs can be added to the resource.
> helm_resource: `links` argument

- kubebuilder/Tiltfile
Was removed in version [0.7.0](https://github.com/kubernetes-sigs/controller-tools/commit/09f1952580d4e40a3aab8b1c4f6bfc8de3ae0b0b) latest is 0.16.2
> Trivial version is not available anymore on later releases

- helm_resource/README.md
- helm_resource/Tiltfile
- helm_resource/helm-delete-helper.py
This is a simple PR that adds an optional argument `uninstall_flags` to the `helm_resource` extension to support the ability to pass custom flags to the `helm uninstall` command. This is similar to the existing `flags` argument which passes custom flags to the `helm upgrade --install` command.
> [helm_resource] Support specifying custom helm uninstall flags

- helm_remote/Tiltfile
Adds `helm_remote_yaml`
Example use case would be generating the yaml with helm and then applying some transformations before installing.
> add helm_remote_yaml

- helm_remote/Tiltfile
- helm_remote/test/Tiltfile
Using OCI charts currently fails on master with:
```
Error in local: command "helm repo add prometheus oci://ghcr.io/prometheus-community/charts" failed.
error: exit status 1
```
> Fix helm_remote for OCI registries and add test

- restart_process/tilt-restart-wrapper.go
In #586 support for forwarding **all** signals sent to PID 1 on to `entr` was added. However, it doesn’t fully address the goal of #577, since the developer’s "true" entrypoint isn’t receiving those forwarded signals—only `entr` is. While this generally works for shutting down child processes, it can also forward unintended signals that break `entr`.
A concrete example is when the child process managed by `entr` becomes a zombie and gets re-parented to PID 1. The kernel then sends `SIGCHLD` to PID 1, which in turn forwards it to `entr`. These "spurious" `SIGCHLD` signals can cause `entr` to stop monitoring or restarting the process, breaking the `restart_wrapper` functionality.
1. `kubectl exec` into a pod that uses `restart_wrapper`.
2. Run `kill -SIGCHLD <entr-pid>`.
3. After this, Tilt …
> restart_wrapper: Be explicit about what signals are forwarded to entr

- podman/README.md
- podman/Tiltfile
`podman_build` currently doesn't let you pass through arguments to `podman push`. This PR adds this feature
> Add optional push flags

- helm_resource/Tiltfile
- helm_resource/helm-apply-helper.py
The `update_dependencies` flag will auto-bump versions in the `Chart.lock`. This isn't desirable in all situations. However, it's still useful to have the tilt managed `helm_resource` download (build) the dependencies in the first place.
Note: I'm not a tilt maintainer and unsure anything else that would need to be done here. I might suspect some test could be worth doing as well.
> Add build_dependencies flag to helm_resource

- coreos_prometheus/Tiltfile
This bumps the kube-prometheus operator release to 0.15.0. This is because according to this [1] compatibility table, 0.14.0 is not supported by versions Kubernetes >= 1.32
This also removes the operator resource dependency for the CRDs. This inclusion means that the operator pod is started before the CRDs. This results in the pod not being able to read Prometheus or Alertmanager CRD resources, so the resulting pods are never created until the operator pod is restarted. Creating the CRDs before the operator pod fixes this problem.
[1] https://github.com/prometheus-operator/kube-prometheus?tab=readme-ov-file#compatibility
> coreos_prometheus: bump to 0.15, remove operator dep
